- name: autopy-lot
  # You may pin to the exact commit or the version.
  # uses: deep5050/autopy-lot@e24587891d74156aeb8ad10ad76506cb0126c965
  uses: deep5050/autopy-lot@1.1
  with:
    # GITHUB_TOKEN secret < automatically provided by Github , you don't need to set up >
    github_token: 
    # Which files to check: all or just committed: all | latest
    check: # optional, default is all
    # File types to be converted : py | ipynb | r 
    input_type: # optional, default is ipynb
    # --opt comment_magics <see documentation> : false (default) | true 
    comment_magics: # optional, default is 
    # --opt split_at_heading <see documentation> :false (default) | true
    split_at_heading: # optional, default is 
    # Target output type: py | markdown | rmarkdown | r | ipynb
    output_type: markdown # optional, default is py
    # Branch that the badge will target. Defaults to the current branch.
    target_branch: # optional, default is 
    # Branch that the badge will target on pull_request. Defaults to GITHUB_BASE_REF.
    pull_request_branch: # optional, default is 
    # Repository that the badge will target. Defaults to the current repository.
    target_repository: # optional, default is 
    # Repository that the badge will target on pull_request. Defaults to TARGET_REPOSITORY
    pull_request_repository: # optional, default is 
